# Generated by Django 2.0.3 on 2020-11-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0002_position_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='price',
            new_name='purchase_price',
        ),
    ]
